import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";
import "tailwindcss/tailwind.css";
import Welcome from "../components/Welcome";
import Intro from "../components/Intro";
import NextSetup from "../components/NextSetup";
import AddWeb3 from "../components/AddWeb3";
import ProviderAndNetwork from "../components/ProviderAndNetwork";
import UsingConnectWallet from "../components/UsingConnectWallet";
import UsingAddress from "../components/UsingAddress";
const Home = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Welcome />
      <Intro />
      <NextSetup />
      <AddWeb3 />
      <ProviderAndNetwork />
      <UsingConnectWallet />
      <UsingAddress />
      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{" "}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  );
};

export default Home;
