import Head from "next/head";
import Image from "next/image";
import Link from "next/link";
import styles from "../styles/Home.module.css";
import "tailwindcss/tailwind.css";
import Welcome from "../components/Welcome";
import Intro from "../components/Intro";
import NextSetup from "../components/NextSetup";
import AddWeb3 from "../components/AddWeb3";
import ProviderAndNetwork from "../components/ProviderAndNetwork";

const Home = () => {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Welcome />
      <Intro />
      <NextSetup />
      <AddWeb3 />
      <ProviderAndNetwork />
      <div
        className="flex flex-col lg:flex-row-reverse w-full min-h-screen h-full justify-center items-center bg-slate-200"
        id="nextpage"
      >
        <div className="flex flex-col justify-center items-center p-10">
          <p className="p-4 text-lg w-4/5 leading-10">
            Great! Now we are ready to dive into some basic components and
            hooks!
          </p>
          <p className="p-4 text-lg w-4/5 leading-10 m-4">
            Let&apos;s continue on the next page
          </p>
          <Link href="/basics">
            <p className="py-4 px-8 hover:cursor-pointer bg-slate-600 rounded-lg text-slate-100">
              next
            </p>
          </Link>
        </div>
      </div>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{" "}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  );
};

export default Home;
